Chunk_table:	equ	$FF0000
LevelSelectRSDK_buffer:	equ	$FF0000
LevelSelect_buffer:	equ	$FF0000
Options_buffer:	equ	$FF0000
SStage_Buffer1:	equ	$FF0000
TitleLevelSelect_buffer:	equ	$FF0000
LevelSelectRSDK_buffer2:	equ	$FF1000
LevelSelect_buffer2:	equ	$FF1000
Options_buffer2:	equ	$FF1000
TitleLevelSelect_buffer2:	equ	$FF1000
TitleLevelSelect_buffer3:	equ	$FF2000
SStage_Buffer2:	equ	$FF4000
SStage_Buffer3:	equ	$FF5000
SStage_Scroll_Buffer:	equ	$FF5400
SStage_Scroll_Buffer2:	equ	$FF5500
SStage_Ghost_Buffer:	equ	$FF5600
Player_1:	equ	$FF8000
Player_2:	equ	$FF8050
Reserved_object_3:	equ	$FF80A0
Dynamic_object_RAM:	equ	$FF80F0
Breathing_bubbles:	equ	$FF9D60
Breathing_bubbles_P2:	equ	$FF9DB0
Super_stars:	equ	$FF9E00
Tails_tails:	equ	$FF9E50
Dust:	equ	$FF9EA0
Dust_P2:	equ	$FF9EF0
Shield:	equ	$FF9F40
Invincibility_stars:	equ	$FF9FE0
Water_Splash:	equ	$FFA1C0
Wave_Splash:	equ	$FFA210
KosPlus_decomp_buffer:	equ	$FFA294
H_scroll_buffer:	equ	$FFB294
H_scroll_table:	equ	$FFB614
V_scroll_buffer:	equ	$FFB814
Collision_response_list:	equ	$FFB864
Pos_table_P2:	equ	$FFB8E4
Pos_table:	equ	$FFB9E4
Ring_status_table:	equ	$FFBAE4
Object_respawn_table:	equ	$FFBEE4
Sprite_table_buffer:	equ	$FFC1E4
Sprite_table_input:	equ	$FFC464
DMA_queue:	equ	$FFC864
DMA_queue_slot:	equ	$FFC960
H_scroll_amount:	equ	$FFC962
V_scroll_amount:	equ	$FFC964
H_scroll_amount_P2:	equ	$FFC966
V_scroll_amount_P2:	equ	$FFC968
Camera_target_min_X_pos:	equ	$FFC96A
Camera_target_max_X_pos:	equ	$FFC96C
Camera_target_min_Y_pos:	equ	$FFC96E
Camera_target_max_Y_pos:	equ	$FFC970
Camera_min_X_pos:	equ	$FFC972
Camera_max_X_pos:	equ	$FFC974
Camera_min_Y_pos:	equ	$FFC976
Camera_max_Y_pos:	equ	$FFC978
Camera_stored_max_X_pos:	equ	$FFC97A
Camera_stored_min_X_pos:	equ	$FFC97C
Camera_stored_min_Y_pos:	equ	$FFC97E
Camera_stored_max_Y_pos:	equ	$FFC980
Camera_saved_min_X_pos:	equ	$FFC982
Camera_saved_max_X_pos:	equ	$FFC984
Camera_saved_min_Y_pos:	equ	$FFC986
Camera_saved_max_Y_pos:	equ	$FFC988
H_scroll_frame_offset:	equ	$FFC98A
Pos_table_index:	equ	$FFC98C
Pos_table_byte:	equ	$FFC98D
H_scroll_frame_offset_P2:	equ	$FFC98E
Pos_table_index_P2:	equ	$FFC990
Pos_table_byte_P2:	equ	$FFC991
Distance_from_top:	equ	$FFC992
Distance_from_top_P2:	equ	$FFC994
Camera_max_Y_pos_changing:	equ	$FFC996
Fast_V_scroll_flag:	equ	$FFC998
Scroll_lock:	equ	$FFC999
Camera_X_diff:	equ	$FFC99A
Camera_Y_diff:	equ	$FFC99C
Camera_X_pos:	equ	$FFC99E
Camera_Y_pos:	equ	$FFC9A2
Camera_X_pos_copy:	equ	$FFC9A6
Camera_Y_pos_copy:	equ	$FFC9AA
Camera_X_pos_rounded:	equ	$FFC9AE
Camera_Y_pos_rounded:	equ	$FFC9B0
Camera_X_pos_BG_copy:	equ	$FFC9B2
Camera_Y_pos_BG_copy:	equ	$FFC9B6
Camera_X_pos_BG_rounded:	equ	$FFC9BA
Camera_Y_pos_BG_rounded:	equ	$FFC9BC
Camera_X_pos_coarse:	equ	$FFC9BE
Camera_Y_pos_coarse:	equ	$FFC9C0
Camera_X_pos_coarse_back:	equ	$FFC9C2
Camera_Y_pos_coarse_back:	equ	$FFC9C4
Plane_double_update_flag:	equ	$FFC9C6
Special_V_int_routine:	equ	$FFC9C7
Camera_H_scroll_shift:	equ	$FFC9C8
Camera_X_center:	equ	$FFC9CE
Screen_X_wrap_value:	equ	$FFC9D0
Screen_Y_wrap_value:	equ	$FFC9D2
Camera_Y_pos_mask:	equ	$FFC9D4
Layout_row_index_mask:	equ	$FFC9D6
Scroll_force_positions:	equ	$FFC9D8
Scroll_forced_X_pos:	equ	$FFC9DA
Scroll_forced_Y_pos:	equ	$FFC9DE
Glide_screen_shake:	equ	$FFC9E2
Screen_shaking_flag:	equ	$FFC9E4
Screen_shaking_offset:	equ	$FFC9E6
Screen_shaking_last_offset:	equ	$FFC9E8
Level_repeat_offset:	equ	$FFC9EA
Spritemask_flag:	equ	$FFC9EC
Events_fg:	equ	$FFC9EE
Draw_delayed_position:	equ	$FFCA06
Draw_delayed_rowcount:	equ	$FFCA08
Events_bg:	equ	$FFCA0A
Boss_events:	equ	$FFCA22
Title_cheat_counter:	equ	$FFCA22
Title_control:	equ	$FFCA23
Title_end:	equ	$FFCA24
Plane_buffer_2_addr:	equ	$FFCA42
Ring_start_addr_ROM:	equ	$FFCA46
Ring_end_addr_ROM:	equ	$FFCA4A
Ring_start_addr_RAM:	equ	$FFCA4E
Ring_consumption_count:	equ	$FFCA50
Ring_consumption_list:	equ	$FFCA52
Plane_buffer:	equ	$FFCAD0
Game_mode:	equ	$FFCF50
Plane_buffer_end:	equ	$FFCF50
V_int_routine:	equ	$FFCF51
Ctrl_1_held_logical:	equ	$FFCF52
Ctrl_1_pressed_logical:	equ	$FFCF53
Ctrl_1_held:	equ	$FFCF54
Ctrl_1_pressed:	equ	$FFCF55
Ctrl_2_held:	equ	$FFCF56
Ctrl_2_pressed:	equ	$FFCF57
Ctrl_2_held_logical:	equ	$FFCF58
Ctrl_2_pressed_logical:	equ	$FFCF59
VDP_reg_1_command:	equ	$FFCF5A
Demo_timer:	equ	$FFCF5C
V_scroll_value_FG:	equ	$FFCF5E
V_scroll_value_BG:	equ	$FFCF60
H_scroll_value_FG:	equ	$FFCF62
H_scroll_value_BG:	equ	$FFCF64
H_int_counter_command:	equ	$FFCF66
H_int_counter:	equ	$FFCF67
RNG_seed:	equ	$FFCF68
Palette_fade_index:	equ	$FFCF6C
Palette_fade_count:	equ	$FFCF6D
Player_StoodOnPlatform:	equ	$FFCF6E
Player_ResetOnFloor:	equ	$FFCF6F
Lag_frame_count:	equ	$FFCF70
H_int_flag:	equ	$FFCF72
Do_Updates_in_H_int:	equ	$FFCF73
WindTunnel_holding_flag:	equ	$FFCF74
WindTunnel_flag:	equ	$FFCF75
WindTunnel_flag_P2:	equ	$FFCF76
Disable_death_plane:	equ	$FFCF77
Ctrl_1_locked:	equ	$FFCF78
Ctrl_2_locked:	equ	$FFCF79
Level_frame_counter:	equ	$FFCF7A
Level_started_flag:	equ	$FFCF7C
Game_paused:	equ	$FFCF7D
Restart_level_flag:	equ	$FFCF7E
Sprites_drawn:	equ	$FFCF7F
Max_speed:	equ	$FFCF80
Acceleration:	equ	$FFCF82
Deceleration:	equ	$FFCF84
Max_speed_P2:	equ	$FFCF86
Acceleration_P2:	equ	$FFCF88
Deceleration_P2:	equ	$FFCF8A
Credits_routine:	equ	$FFCF8C
LevelSelectRSDK_music_count:	equ	$FFCF8C
LevelSelect_music_count:	equ	$FFCF8C
Object_load_addr_front:	equ	$FFCF8C
Options_music_count:	equ	$FFCF8C
TitleLevelSelect_music_count:	equ	$FFCF8C
Credits_process:	equ	$FFCF8E
LevelSelectRSDK_sound_count:	equ	$FFCF8E
LevelSelect_sound_count:	equ	$FFCF8E
Options_sound_count:	equ	$FFCF8E
TitleLevelSelect_sound_count:	equ	$FFCF8E
LevelSelectRSDK_sample_count:	equ	$FFCF90
LevelSelect_sample_count:	equ	$FFCF90
Object_load_addr_back:	equ	$FFCF90
Options_sample_count:	equ	$FFCF90
TitleLevelSelect_sample_count:	equ	$FFCF90
Credits_process_time:	equ	$FFCF92
LevelSelectRSDK_control_timer:	equ	$FFCF92
LevelSelect_control_timer:	equ	$FFCF92
Options_save_music:	equ	$FFCF92
TitleLevelSelect_control_timer:	equ	$FFCF92
Credits_end:	equ	$FFCF94
LevelSelectRSDK_saved_act:	equ	$FFCF94
LevelSelect_saved_act:	equ	$FFCF94
Object_respawn_index_front:	equ	$FFCF94
Options_control_timer:	equ	$FFCF94
TitleLevelSelect_saved_act:	equ	$FFCF94
LevelSelectRSDK_cheat_counter:	equ	$FFCF96
LevelSelect_cheat_counter:	equ	$FFCF96
Object_respawn_index_back:	equ	$FFCF96
Options_vertical_count:	equ	$FFCF96
TitleLevelSelect_cheat_counter:	equ	$FFCF96
Collision_addr:	equ	$FFCF98
LevelSelectRSDK_cheat_counter2:	equ	$FFCF98
LevelSelect_cheat_counter2:	equ	$FFCF98
TitleLevelSelect_cheat_counter2:	equ	$FFCF98
LevelSelectRSDK_vertical_count:	equ	$FFCF9A
LevelSelect_vertical_count:	equ	$FFCF9A
TitleLevelSelect_vertical_count:	equ	$FFCF9A
LevelSelectRSDK_vertical_count_prev:	equ	$FFCF9C
LevelSelect_horizontal_count:	equ	$FFCF9C
Primary_collision_addr:	equ	$FFCF9C
Secondary_collision_addr:	equ	$FFCFA0
Player_prev_frame:	equ	$FFCFA4
Player_prev_frame_P2:	equ	$FFCFA5
Player_prev_frame_P2_tail:	equ	$FFCFA6
Reverse_gravity_flag:	equ	$FFCFA7
Primary_Angle:	equ	$FFCFA8
Primary_Angle_save:	equ	$FFCFA9
Secondary_Angle:	equ	$FFCFAA
Secondary_Angle_save:	equ	$FFCFAB
Deform_lock:	equ	$FFCFAC
Boss_flag:	equ	$FFCFAD
Level_results_flag:	equ	$FFCFAE
End_of_level_flag:	equ	$FFCFAF
Special_events_addr:	equ	$FFCFB0
NoBackground_event_flag:	equ	$FFCFB4
Screen_event_routine:	equ	$FFCFB5
Screen_event_flag:	equ	$FFCFB6
Background_event_routine:	equ	$FFCFB7
Background_event_flag:	equ	$FFCFB8
Background_collision_flag:	equ	$FFCFB9
Debug_placement_routine:	equ	$FFCFBA
Debug_placement_type:	equ	$FFCFBB
Debug_camera_delay:	equ	$FFCFBC
Debug_camera_speed:	equ	$FFCFBD
Debug_object:	equ	$FFCFBE
Last_act_end_flag:	equ	$FFCFBF
Slotted_object_bits:	equ	$FFCFC0
Signpost_addr:	equ	$FFCFC8
Render_sprite_first_RAM:	equ	$FFCFCA
Render_sprite_last_RAM:	equ	$FFCFEA
Chain_stomp_addr:	equ	$FFCFEE
Push_block_addr:	equ	$FFCFF0
Float_block_flag:	equ	$FFCFF2
Scrap_stomp_flag:	equ	$FFCFF3
_unkFAAC:	equ	$FFCFF4
Convey_rev_flag:	equ	$FFCFF5
Convey_rev_buffer:	equ	$FFCFF6
Continue_countdown:	equ	$FFCFFC
Palette_cycle_counters:	equ	$FFCFFC
SStage_scalar_index_0:	equ	$FFCFFC
Continue_routine:	equ	$FFCFFE
SStage_scalar_index_1:	equ	$FFCFFE
Continue_countdown_numbers:	equ	$FFCFFF
Continue_countdown_update:	equ	$FFD000
v_palss_num:	equ	$FFD000
v_palss_time:	equ	$FFD002
v_ssbganim:	equ	$FFD004
v_bg3screenposx:	equ	$FFD006
v_ani0_time:	equ	$FFD00A
v_ani0_frame:	equ	$FFD00B
v_ani2_time:	equ	$FFD00C
v_ani2_frame:	equ	$FFD00D
v_ani3_time:	equ	$FFD00E
v_ani3_frame:	equ	$FFD00F
Special_stage_flag:	equ	$FFD010
Special_stage_ring_count:	equ	$FFD012
Emerald_flicker_flag:	equ	$FFD014
Special_stage_spheres_left:	equ	$FFD016
Special_stage_rings_left:	equ	$FFD018
Saved_special_stage:	equ	$FFD01A
Palette_frame:	equ	$FFD03C
Palette_timer:	equ	$FFD03E
Super_palette_status:	equ	$FFD03F
Palette_frame_Tails:	equ	$FFD040
Palette_timer_Tails:	equ	$FFD041
Pal_fade_delay:	equ	$FFD042
Pal_fade_delay2:	equ	$FFD044
Super_frame_count:	equ	$FFD046
Scalar_factor:	equ	$FFD048
Music_results_flag:	equ	$FFD04A
Super_Sonic_Knux_flag:	equ	$FFD04B
Super_Tails_flag:	equ	$FFD04C
Hyper_Sonic_flash_timer:	equ	$FFD04D
Negative_flash_timer:	equ	$FFD04E
Palette_rotation_disable:	equ	$FFD04F
Palette_rotation_custom:	equ	$FFD050
Palette_rotation_data:	equ	$FFD054
Chain_bonus_counter:	equ	$FFD066
Time_bonus_countdown:	equ	$FFD068
Ring_bonus_countdown:	equ	$FFD06A
Total_bonus_countup:	equ	$FFD06C
Tails_CPU_interact:	equ	$FFD06E
Tails_CPU_idle_timer:	equ	$FFD070
Tails_CPU_flight_timer:	equ	$FFD072
Tails_CPU_routine:	equ	$FFD076
Tails_CPU_target_X:	equ	$FFD078
Tails_CPU_target_Y:	equ	$FFD07A
Tails_CPU_auto_fly_timer:	equ	$FFD07C
Tails_CPU_auto_jump_flag:	equ	$FFD07D
Flying_carrying_Sonic_flag:	equ	$FFD07E
Flying_picking_Sonic_timer:	equ	$FFD07F
_unkF744:	equ	$FFD080
_unkF74A:	equ	$FFD082
_unkF74B:	equ	$FFD083
_unkF74C:	equ	$FFD084
Tails_CPU_star_post_flag:	equ	$FFD086
_unkF66C:	equ	$FFD087
Knuckles_saved_frame:	equ	$FFD089
Gliding_collision_flags:	equ	$FFD08A
Disable_wall_grab:	equ	$FFD08B
Water_level:	equ	$FFD08C
Mean_water_level:	equ	$FFD08E
Target_water_level:	equ	$FFD090
Water_speed:	equ	$FFD092
Water_entered_counter:	equ	$FFD093
Water_full_screen_flag:	equ	$FFD094
Water_flag:	equ	$FFD095
Block_table_addr_ROM:	equ	$FFD096
Level_chunk_addr_ROM:	equ	$FFD09A
Level_layout_addr_ROM:	equ	$FFD09E
Level_layout_addr2_ROM:	equ	$FFD0A2
Rings_manager_addr_RAM:	equ	$FFD0A6
Object_index_addr:	equ	$FFD0AA
Object_load_addr_RAM:	equ	$FFD0AE
Level_data_addr_RAM.Resize:	equ	$FFD0B2
Level_data_addr_RAM.WaterResize:	equ	$FFD0B6
Level_data_addr_RAM.AfterBoss:	equ	$FFD0BA
Level_data_addr_RAM.AnimatePalette:	equ	$FFD0BE
Level_data_addr_RAM.AnPalScript:	equ	$FFD0C2
Level_data_addr_RAM.ScreenInit:	equ	$FFD0C6
Level_data_addr_RAM.BackgroundInit:	equ	$FFD0CA
Level_data_addr_RAM.ScreenEvent:	equ	$FFD0CE
Level_data_addr_RAM.BackgroundEvent:	equ	$FFD0D2
Level_data_addr_RAM.AnimateTilesInit:	equ	$FFD0D6
Level_data_addr_RAM.AnimateTiles:	equ	$FFD0DA
Level_data_addr_RAM.AnPLCScript:	equ	$FFD0DE
Level_data_addr_RAM.8x8data1:	equ	$FFD0E2
Level_data_addr_RAM.8x8data2:	equ	$FFD0E6
Level_data_addr_RAM.16x16ram:	equ	$FFD0EA
Level_data_addr_RAM.16x16data1:	equ	$FFD0EE
Level_data_addr_RAM.16x16data2:	equ	$FFD0F2
Level_data_addr_RAM.128x128ram:	equ	$FFD0F6
Level_data_addr_RAM.128x128data1:	equ	$FFD0FA
Level_data_addr_RAM.128x128data2:	equ	$FFD0FE
Level_data_addr_RAM.Solid:	equ	$FFD102
Level_data_addr_RAM.Layout:	equ	$FFD106
Level_data_addr_RAM.Sprites:	equ	$FFD10A
Level_data_addr_RAM.Rings:	equ	$FFD10E
Level_data_addr_RAM.PLC1:	equ	$FFD112
Level_data_addr_RAM.PLC2:	equ	$FFD116
Level_data_addr_RAM.PLCAnimals:	equ	$FFD11A
Level_data_addr_RAM.xstart:	equ	$FFD11E
Level_data_addr_RAM.xend:	equ	$FFD120
Level_data_addr_RAM.ystart:	equ	$FFD122
Level_data_addr_RAM.yend:	equ	$FFD124
Level_data_addr_RAM.WaterHeight:	equ	$FFD126
Level_data_addr_RAM.Spal:	equ	$FFD128
Level_data_addr_RAM.Kpal:	equ	$FFD129
Level_data_addr_RAM.WaterSpal:	equ	$FFD12A
Level_data_addr_RAM.WaterKpal:	equ	$FFD12B
Level_data_addr_RAM.Location:	equ	$FFD12C
Level_data_addr_RAM.Debug:	equ	$FFD130
KosPlus_decomp_queue_count:	equ	$FFD134
KosPlus_decomp_stored_registers:	equ	$FFD136
KosPlus_decomp_stored_SR:	equ	$FFD14E
KosPlus_decomp_bookmark:	equ	$FFD150
KosPlus_decomp_queue:	equ	$FFD154
KosPlus_modules_left:	equ	$FFD174
KosPlus_last_module_size:	equ	$FFD176
KosPlus_module_queue:	equ	$FFD178
Target_water_palette_line_1:	equ	$FFD238
Target_water_palette_line_2:	equ	$FFD258
Target_water_palette_line_3:	equ	$FFD278
Target_water_palette_line_4:	equ	$FFD298
Water_palette_line_1:	equ	$FFD2B8
Water_palette_line_2:	equ	$FFD2D8
Water_palette_line_3:	equ	$FFD2F8
Water_palette_line_4:	equ	$FFD318
Normal_palette_line_1:	equ	$FFD338
Normal_palette_line_2:	equ	$FFD358
Normal_palette_line_3:	equ	$FFD378
Normal_palette_line_4:	equ	$FFD398
Target_palette_line_1:	equ	$FFD3B8
Target_palette_line_2:	equ	$FFD3D8
Target_palette_line_3:	equ	$FFD3F8
Target_palette_line_4:	equ	$FFD418
Oscillation_Control:	equ	$FFD438
Oscillating_Data:	equ	$FFD43C
Anim_Counters:	equ	$FFD484
AIZ_vine_angle:	equ	$FFD494
Ending_player:	equ	$FFD496
Level_trigger_array:	equ	$FFD496
Spikes_frame_timer:	equ	$FFD4A6
Spikes_frame:	equ	$FFD4A7
Rings_frame_timer:	equ	$FFD4A8
Rings_frame:	equ	$FFD4A9
Ring_spill_anim_counter:	equ	$FFD4AA
Ring_spill_anim_frame:	equ	$FFD4AB
Ring_spill_anim_accum:	equ	$FFD4AC
Stack_contents:	equ	$FFD4AE
V_int_run_count:	equ	$FFD5AE
Current_zone:	equ	$FFD5B2
Current_act:	equ	$FFD5B3
Apparent_zone:	equ	$FFD5B4
Apparent_act:	equ	$FFD5B5
Player_mode:	equ	$FFD5B6
Player_option:	equ	$FFD5B8
Life_count:	equ	$FFD5BA
Current_special_stage:	equ	$FFD5BB
Continue_count:	equ	$FFD5BC
Chaos_emerald_count:	equ	$FFD5BE
Collected_emeralds_array:	equ	$FFD5C0
Special_bonus_entry_flag:	equ	$FFD5C8
Next_extra_life_score:	equ	$FFD5CA
Debug_saved_mappings:	equ	$FFD5CE
Debug_saved_priority:	equ	$FFD5D2
Debug_saved_art_tile:	equ	$FFD5D4
Last_star_post_hit:	equ	$FFD5D7
Current_music:	equ	$FFD5D8
Palette_fade_timer:	equ	$FFD5DA
Respawn_table_keep:	equ	$FFD5DC
Intro_flag:	equ	$FFD5DD
Music_disable_flag:	equ	$FFD5DE
Sound_disable_flag:	equ	$FFD5DF
Graphics_flags:	equ	$FFD5E0
Level_select_flag:	equ	$FFD5E1
Debug_mode_flag:	equ	$FFD5E2
SBZ2_player_roll:	equ	$FFD5E3
Japan_credits_flag:	equ	$FFD5E4
Debug_cheat_flag:	equ	$FFD5E5
Game_mode_last:	equ	$FFD5E6
Time_over_flag:	equ	$FFD5E8
Extra_life_flags:	equ	$FFD5E9
Update_HUD_life_count:	equ	$FFD5EA
Update_HUD_ring_count:	equ	$FFD5EB
Update_HUD_timer:	equ	$FFD5EC
Update_HUD_score:	equ	$FFD5ED
Ring_count:	equ	$FFD5EE
Timer:	equ	$FFD5F0
Timer_minute:	equ	$FFD5F1
Timer_second:	equ	$FFD5F2
Timer_frame:	equ	$FFD5F3
Score:	equ	$FFD5F4
HUD_RAM.xpos:	equ	$FFD5F8
HUD_RAM.ypos:	equ	$FFD5FA
HUD_RAM.status:	equ	$FFD5FC
GameOver_RAM.xpos:	equ	$FFD5FE
GameOver_RAM.ypos:	equ	$FFD600
GameOver_RAM.xpos2:	equ	$FFD602
GameOver_RAM.mappings:	equ	$FFD604
GameOver_RAM.timer:	equ	$FFD608
GameOver_RAM.status:	equ	$FFD60A
GameOver_RAM.frame:	equ	$FFD60B
DecimalScoreRAM:	equ	$FFD60C
DecimalScoreRAM2:	equ	$FFD610
Saved_zone_and_act:	equ	$FFD614
Saved_apparent_zone_and_act:	equ	$FFD616
Saved_X_pos:	equ	$FFD618
Saved_Y_pos:	equ	$FFD61A
Saved_ring_count:	equ	$FFD61C
Saved_timer:	equ	$FFD61E
Saved_art_tile:	equ	$FFD622
Saved_solid_bits:	equ	$FFD624
Saved_camera_X_pos:	equ	$FFD626
Saved_camera_Y_pos:	equ	$FFD628
Saved_mean_water_level:	equ	$FFD62A
Saved_water_full_screen_flag:	equ	$FFD62C
Saved_extra_life_flags:	equ	$FFD62D
Saved_camera_max_Y_pos:	equ	$FFD62E
Saved_dynamic_resize:	equ	$FFD630
Saved_waterdynamic_resize:	equ	$FFD634
Saved_status_secondary:	equ	$FFD638
Saved_last_star_post_hit:	equ	$FFD639
Saved2_zone_and_act:	equ	$FFD63A
Saved2_apparent_zone_and_act:	equ	$FFD63C
Saved2_X_pos:	equ	$FFD63E
Saved2_Y_pos:	equ	$FFD640
Saved2_ring_count:	equ	$FFD642
Saved2_timer:	equ	$FFD644
Saved2_art_tile:	equ	$FFD648
Saved2_solid_bits:	equ	$FFD64A
Saved2_camera_X_pos:	equ	$FFD64C
Saved2_camera_Y_pos:	equ	$FFD64E
Saved2_mean_water_level:	equ	$FFD650
Saved2_water_full_screen_flag:	equ	$FFD652
Saved2_extra_life_flags:	equ	$FFD653
Saved2_camera_max_Y_pos:	equ	$FFD654
Saved2_dynamic_resize:	equ	$FFD656
Saved2_waterdynamic_resize:	equ	$FFD65A
Saved2_status_secondary:	equ	$FFD65E
Saved2_last_star_post_hit:	equ	$FFD65F
Demo_start_button:	equ	$FFD660
Demo_mode_flag:	equ	$FFD661
Demo_data_addr:	equ	$FFD662
Demo_hold_counter:	equ	$FFD666
Demo_hold_buttons:	equ	$FFD667
Demo_number:	equ	$FFD668
Next_demo_number:	equ	$FFD66A
Demo_button_index:	equ	$FFD66C
Demo_button_index_2P:	equ	$FFD66E
Checksum_string:	equ	$FFD670
V_int_jump:	equ	$FFD674
V_int_addr:	equ	$FFD676
H_int_jump:	equ	$FFD67A
H_int_addr:	equ	$FFD67C
