Chunk_table:	equ	$FF0000
LevelSelectRSDK_buffer:	equ	$FF0000
LevelSelect_buffer:	equ	$FF0000
Options_buffer:	equ	$FF0000
SStage_Buffer1:	equ	$FF0000
TitleLevelSelect_buffer:	equ	$FF0000
LevelSelectRSDK_buffer2:	equ	$FF1000
LevelSelect_buffer2:	equ	$FF1000
Options_buffer2:	equ	$FF1000
TitleLevelSelect_buffer2:	equ	$FF1000
TitleLevelSelect_buffer3:	equ	$FF2000
SStage_Buffer2:	equ	$FF4000
SStage_Buffer3:	equ	$FF5000
SStage_Scroll_Buffer:	equ	$FF5400
SStage_Scroll_Buffer2:	equ	$FF5500
SStage_Ghost_Buffer:	equ	$FF5600
Player_1:	equ	$FF8000
Player_2:	equ	$FF8050
Reserved_object_3:	equ	$FF80A0
Dynamic_object_RAM:	equ	$FF80F0
Breathing_bubbles:	equ	$FF9D60
Breathing_bubbles_P2:	equ	$FF9DB0
Super_stars:	equ	$FF9E00
Tails_tails:	equ	$FF9E50
Dust:	equ	$FF9EA0
Dust_P2:	equ	$FF9EF0
Shield:	equ	$FF9F40
Invincibility_stars:	equ	$FF9FE0
Water_Splash:	equ	$FFA1C0
Wave_Splash:	equ	$FFA210
KosPlus_decomp_buffer:	equ	$FFA260
H_scroll_buffer:	equ	$FFB260
H_scroll_table:	equ	$FFB5E0
V_scroll_buffer:	equ	$FFB7E0
Collision_response_list:	equ	$FFB830
Pos_table_P2:	equ	$FFB8B0
Pos_table:	equ	$FFB9B0
Ring_status_table:	equ	$FFBAB0
Object_respawn_table:	equ	$FFBEB0
Sprite_table_buffer:	equ	$FFC1B0
Sprite_table_input:	equ	$FFC430
DMA_queue:	equ	$FFC830
DMA_queue_slot:	equ	$FFC92C
H_scroll_amount:	equ	$FFC92E
V_scroll_amount:	equ	$FFC930
H_scroll_amount_P2:	equ	$FFC932
V_scroll_amount_P2:	equ	$FFC934
Camera_target_min_X_pos:	equ	$FFC936
Camera_target_max_X_pos:	equ	$FFC938
Camera_target_min_Y_pos:	equ	$FFC93A
Camera_target_max_Y_pos:	equ	$FFC93C
Camera_min_X_pos:	equ	$FFC93E
Camera_max_X_pos:	equ	$FFC940
Camera_min_Y_pos:	equ	$FFC942
Camera_max_Y_pos:	equ	$FFC944
Camera_stored_max_X_pos:	equ	$FFC946
Camera_stored_min_X_pos:	equ	$FFC948
Camera_stored_min_Y_pos:	equ	$FFC94A
Camera_stored_max_Y_pos:	equ	$FFC94C
Camera_saved_min_X_pos:	equ	$FFC94E
Camera_saved_max_X_pos:	equ	$FFC950
Camera_saved_min_Y_pos:	equ	$FFC952
Camera_saved_max_Y_pos:	equ	$FFC954
H_scroll_frame_offset:	equ	$FFC956
Pos_table_index:	equ	$FFC958
Pos_table_byte:	equ	$FFC959
H_scroll_frame_offset_P2:	equ	$FFC95A
Pos_table_index_P2:	equ	$FFC95C
Pos_table_byte_P2:	equ	$FFC95D
Distance_from_top:	equ	$FFC95E
Distance_from_top_P2:	equ	$FFC960
Camera_max_Y_pos_changing:	equ	$FFC962
Fast_V_scroll_flag:	equ	$FFC964
Scroll_lock:	equ	$FFC965
Camera_X_diff:	equ	$FFC966
Camera_Y_diff:	equ	$FFC968
Camera_X_pos:	equ	$FFC96A
Camera_Y_pos:	equ	$FFC96E
Camera_X_pos_copy:	equ	$FFC972
Camera_Y_pos_copy:	equ	$FFC976
Camera_X_pos_rounded:	equ	$FFC97A
Camera_Y_pos_rounded:	equ	$FFC97C
Camera_X_pos_BG_copy:	equ	$FFC97E
Camera_Y_pos_BG_copy:	equ	$FFC982
Camera_X_pos_BG_rounded:	equ	$FFC986
Camera_Y_pos_BG_rounded:	equ	$FFC988
Camera_X_pos_coarse:	equ	$FFC98A
Camera_Y_pos_coarse:	equ	$FFC98C
Camera_X_pos_coarse_back:	equ	$FFC98E
Camera_Y_pos_coarse_back:	equ	$FFC990
Plane_double_update_flag:	equ	$FFC992
Special_V_int_routine:	equ	$FFC993
Camera_H_scroll_shift:	equ	$FFC994
Screen_X_wrap_value:	equ	$FFC99A
Screen_Y_wrap_value:	equ	$FFC99C
Camera_Y_pos_mask:	equ	$FFC99E
Layout_row_index_mask:	equ	$FFC9A0
Scroll_force_positions:	equ	$FFC9A2
Scroll_forced_X_pos:	equ	$FFC9A4
Scroll_forced_Y_pos:	equ	$FFC9A8
Glide_screen_shake:	equ	$FFC9AC
Screen_shaking_flag:	equ	$FFC9AE
Screen_shaking_offset:	equ	$FFC9B0
Screen_shaking_last_offset:	equ	$FFC9B2
Level_repeat_offset:	equ	$FFC9B4
Spritemask_flag:	equ	$FFC9B6
Events_fg:	equ	$FFC9B8
Draw_delayed_position:	equ	$FFC9D0
Draw_delayed_rowcount:	equ	$FFC9D2
Events_bg:	equ	$FFC9D4
Boss_events:	equ	$FFC9EC
Title_cheat_counter:	equ	$FFC9EC
Title_control:	equ	$FFC9ED
Title_end:	equ	$FFC9EE
Plane_buffer_2_addr:	equ	$FFCA0C
Ring_start_addr_ROM:	equ	$FFCA10
Ring_end_addr_ROM:	equ	$FFCA14
Ring_start_addr_RAM:	equ	$FFCA18
Ring_consumption_count:	equ	$FFCA1A
Ring_consumption_list:	equ	$FFCA1C
Plane_buffer:	equ	$FFCA9A
Game_mode:	equ	$FFCF1A
Plane_buffer_end:	equ	$FFCF1A
V_int_routine:	equ	$FFCF1B
Ctrl_1_held_logical:	equ	$FFCF1C
Ctrl_1_pressed_logical:	equ	$FFCF1D
Ctrl_1_held:	equ	$FFCF1E
Ctrl_1_pressed:	equ	$FFCF1F
Ctrl_2_held:	equ	$FFCF20
Ctrl_2_pressed:	equ	$FFCF21
Ctrl_2_held_logical:	equ	$FFCF22
Ctrl_2_pressed_logical:	equ	$FFCF23
VDP_reg_1_command:	equ	$FFCF24
Demo_timer:	equ	$FFCF26
V_scroll_value_FG:	equ	$FFCF28
V_scroll_value_BG:	equ	$FFCF2A
H_scroll_value_FG:	equ	$FFCF2C
H_scroll_value_BG:	equ	$FFCF2E
H_int_counter_command:	equ	$FFCF30
H_int_counter:	equ	$FFCF31
RNG_seed:	equ	$FFCF32
Palette_fade_index:	equ	$FFCF36
Palette_fade_count:	equ	$FFCF37
Player_StoodOnPlatform:	equ	$FFCF38
Player_ResetOnFloor:	equ	$FFCF39
Lag_frame_count:	equ	$FFCF3A
H_int_flag:	equ	$FFCF3C
Do_Updates_in_H_int:	equ	$FFCF3D
WindTunnel_holding_flag:	equ	$FFCF3E
WindTunnel_flag:	equ	$FFCF3F
WindTunnel_flag_P2:	equ	$FFCF40
Disable_death_plane:	equ	$FFCF41
Ctrl_1_locked:	equ	$FFCF42
Ctrl_2_locked:	equ	$FFCF43
Level_frame_counter:	equ	$FFCF44
Level_started_flag:	equ	$FFCF46
Game_paused:	equ	$FFCF47
Restart_level_flag:	equ	$FFCF48
Sprites_drawn:	equ	$FFCF49
Max_speed:	equ	$FFCF4A
Acceleration:	equ	$FFCF4C
Deceleration:	equ	$FFCF4E
Max_speed_P2:	equ	$FFCF50
Acceleration_P2:	equ	$FFCF52
Deceleration_P2:	equ	$FFCF54
Credits_routine:	equ	$FFCF56
LevelSelectRSDK_music_count:	equ	$FFCF56
LevelSelect_music_count:	equ	$FFCF56
Object_load_addr_front:	equ	$FFCF56
Options_music_count:	equ	$FFCF56
TitleLevelSelect_music_count:	equ	$FFCF56
Credits_process:	equ	$FFCF58
LevelSelectRSDK_sound_count:	equ	$FFCF58
LevelSelect_sound_count:	equ	$FFCF58
Options_sound_count:	equ	$FFCF58
TitleLevelSelect_sound_count:	equ	$FFCF58
LevelSelectRSDK_sample_count:	equ	$FFCF5A
LevelSelect_sample_count:	equ	$FFCF5A
Object_load_addr_back:	equ	$FFCF5A
Options_sample_count:	equ	$FFCF5A
TitleLevelSelect_sample_count:	equ	$FFCF5A
Credits_process_time:	equ	$FFCF5C
LevelSelectRSDK_control_timer:	equ	$FFCF5C
LevelSelect_control_timer:	equ	$FFCF5C
Options_save_music:	equ	$FFCF5C
TitleLevelSelect_control_timer:	equ	$FFCF5C
Credits_end:	equ	$FFCF5E
LevelSelectRSDK_saved_act:	equ	$FFCF5E
LevelSelect_saved_act:	equ	$FFCF5E
Object_respawn_index_front:	equ	$FFCF5E
Options_control_timer:	equ	$FFCF5E
TitleLevelSelect_saved_act:	equ	$FFCF5E
LevelSelectRSDK_cheat_counter:	equ	$FFCF60
LevelSelect_cheat_counter:	equ	$FFCF60
Object_respawn_index_back:	equ	$FFCF60
Options_vertical_count:	equ	$FFCF60
TitleLevelSelect_cheat_counter:	equ	$FFCF60
Collision_addr:	equ	$FFCF62
LevelSelectRSDK_cheat_counter2:	equ	$FFCF62
LevelSelect_cheat_counter2:	equ	$FFCF62
TitleLevelSelect_cheat_counter2:	equ	$FFCF62
LevelSelectRSDK_vertical_count:	equ	$FFCF64
LevelSelect_vertical_count:	equ	$FFCF64
TitleLevelSelect_vertical_count:	equ	$FFCF64
LevelSelectRSDK_vertical_count_prev:	equ	$FFCF66
LevelSelect_horizontal_count:	equ	$FFCF66
Primary_collision_addr:	equ	$FFCF66
Secondary_collision_addr:	equ	$FFCF6A
Player_prev_frame:	equ	$FFCF6E
Player_prev_frame_P2:	equ	$FFCF6F
Player_prev_frame_P2_tail:	equ	$FFCF70
Player_prev_bank:	equ	$FFCF71
Player_prev_bank_P2:	equ	$FFCF72
Player_prev_bank_P2_tail:	equ	$FFCF73
Player_curr_bank:	equ	$FFCF74
Player_curr_bank_P2:	equ	$FFCF75
Reverse_gravity_flag:	equ	$FFCF77
Primary_Angle:	equ	$FFCF78
Primary_Angle_save:	equ	$FFCF79
Secondary_Angle:	equ	$FFCF7A
Secondary_Angle_save:	equ	$FFCF7B
Deform_lock:	equ	$FFCF7C
Boss_flag:	equ	$FFCF7D
Level_results_flag:	equ	$FFCF7E
End_of_level_flag:	equ	$FFCF7F
Special_events_addr:	equ	$FFCF80
NoBackground_event_flag:	equ	$FFCF84
Screen_event_routine:	equ	$FFCF85
Screen_event_flag:	equ	$FFCF86
Background_event_routine:	equ	$FFCF87
Background_event_flag:	equ	$FFCF88
Background_collision_flag:	equ	$FFCF89
Debug_placement_routine:	equ	$FFCF8A
Debug_placement_type:	equ	$FFCF8B
Debug_camera_delay:	equ	$FFCF8C
Debug_camera_speed:	equ	$FFCF8D
Debug_object:	equ	$FFCF8E
Last_act_end_flag:	equ	$FFCF8F
Slotted_object_bits:	equ	$FFCF90
Signpost_addr:	equ	$FFCF98
Render_sprite_first_RAM:	equ	$FFCF9A
Render_sprite_last_RAM:	equ	$FFCFBA
Chain_stomp_addr:	equ	$FFCFBE
Push_block_addr:	equ	$FFCFC0
Float_block_flag:	equ	$FFCFC2
Scrap_stomp_flag:	equ	$FFCFC3
_unkFAAC:	equ	$FFCFC4
Convey_rev_flag:	equ	$FFCFC5
Convey_rev_buffer:	equ	$FFCFC6
Continue_countdown:	equ	$FFCFCC
Palette_cycle_counters:	equ	$FFCFCC
SStage_scalar_index_0:	equ	$FFCFCC
Continue_routine:	equ	$FFCFCE
SStage_scalar_index_1:	equ	$FFCFCE
Continue_countdown_numbers:	equ	$FFCFCF
Continue_countdown_update:	equ	$FFCFD0
v_palss_num:	equ	$FFCFD0
v_palss_time:	equ	$FFCFD2
v_ssbganim:	equ	$FFCFD4
v_bg3screenposx:	equ	$FFCFD6
v_ani0_time:	equ	$FFCFDA
v_ani0_frame:	equ	$FFCFDB
v_ani2_time:	equ	$FFCFDC
v_ani2_frame:	equ	$FFCFDD
v_ani3_time:	equ	$FFCFDE
v_ani3_frame:	equ	$FFCFDF
Special_stage_flag:	equ	$FFCFE0
Special_stage_ring_count:	equ	$FFCFE2
Emerald_flicker_flag:	equ	$FFCFE4
Special_stage_spheres_left:	equ	$FFCFE6
Special_stage_rings_left:	equ	$FFCFE8
Saved_special_stage:	equ	$FFCFEA
Palette_frame:	equ	$FFD00C
Palette_timer:	equ	$FFD00E
Super_palette_status:	equ	$FFD00F
Palette_frame_Tails:	equ	$FFD010
Palette_timer_Tails:	equ	$FFD011
Pal_fade_delay:	equ	$FFD012
Pal_fade_delay2:	equ	$FFD014
Scalar_factor:	equ	$FFD016
Super_frame_count:	equ	$FFD018
Super_Sonic_Knux_flag:	equ	$FFD01A
Super_Tails_flag:	equ	$FFD01B
Hyper_Sonic_flash_timer:	equ	$FFD01C
Negative_flash_timer:	equ	$FFD01D
Music_results_flag:	equ	$FFD01E
Palette_rotation_disable:	equ	$FFD01F
Palette_rotation_custom:	equ	$FFD020
Palette_rotation_data:	equ	$FFD024
Chain_bonus_counter:	equ	$FFD036
Time_bonus_countdown:	equ	$FFD038
Ring_bonus_countdown:	equ	$FFD03A
Total_bonus_countup:	equ	$FFD03C
Tails_CPU_interact:	equ	$FFD03E
Tails_CPU_idle_timer:	equ	$FFD040
Tails_CPU_flight_timer:	equ	$FFD042
Tails_CPU_routine:	equ	$FFD046
Tails_CPU_target_X:	equ	$FFD048
Tails_CPU_target_Y:	equ	$FFD04A
Tails_CPU_auto_fly_timer:	equ	$FFD04C
Tails_CPU_auto_jump_flag:	equ	$FFD04D
Flying_carrying_Sonic_flag:	equ	$FFD04E
Flying_picking_Sonic_timer:	equ	$FFD04F
_unkF744:	equ	$FFD050
_unkF74A:	equ	$FFD052
_unkF74B:	equ	$FFD053
_unkF74C:	equ	$FFD054
Tails_CPU_star_post_flag:	equ	$FFD056
_unkF66C:	equ	$FFD057
Gliding_collision_flags:	equ	$FFD058
Disable_wall_grab:	equ	$FFD059
Water_level:	equ	$FFD05A
Mean_water_level:	equ	$FFD05C
Target_water_level:	equ	$FFD05E
Water_speed:	equ	$FFD060
Water_entered_counter:	equ	$FFD061
Water_full_screen_flag:	equ	$FFD062
Water_flag:	equ	$FFD063
Level_layout_addr_ROM:	equ	$FFD064
Level_layout_addr2_ROM:	equ	$FFD068
Rings_manager_addr_RAM:	equ	$FFD06C
Object_index_addr:	equ	$FFD070
Object_load_addr_RAM:	equ	$FFD074
Level_data_addr_RAM.Resize:	equ	$FFD078
Level_data_addr_RAM.WaterResize:	equ	$FFD07C
Level_data_addr_RAM.AfterBoss:	equ	$FFD080
Level_data_addr_RAM.AnimatePalette:	equ	$FFD084
Level_data_addr_RAM.AnPalScript:	equ	$FFD088
Level_data_addr_RAM.ScreenInit:	equ	$FFD08C
Level_data_addr_RAM.BackgroundInit:	equ	$FFD090
Level_data_addr_RAM.ScreenEvent:	equ	$FFD094
Level_data_addr_RAM.BackgroundEvent:	equ	$FFD098
Level_data_addr_RAM.AnimateTilesInit:	equ	$FFD09C
Level_data_addr_RAM.AnimateTiles:	equ	$FFD0A0
Level_data_addr_RAM.AnPLCScript:	equ	$FFD0A4
Level_data_addr_RAM.8x8Data1:	equ	$FFD0A8
Level_data_addr_RAM.8x8Data2:	equ	$FFD0AC
Level_data_addr_RAM.16x16RAM:	equ	$FFD0B0
Level_data_addr_RAM.16x16Data1:	equ	$FFD0B4
Level_data_addr_RAM.16x16Data2:	equ	$FFD0B8
Level_data_addr_RAM.128x128RAM:	equ	$FFD0BC
Level_data_addr_RAM.128x128Data1:	equ	$FFD0C0
Level_data_addr_RAM.128x128Data2:	equ	$FFD0C4
Level_data_addr_RAM.LayoutRAM:	equ	$FFD0C8
Level_data_addr_RAM.LayoutData1:	equ	$FFD0CC
Level_data_addr_RAM.LayoutData2:	equ	$FFD0D0
Level_data_addr_RAM.SolidRAM:	equ	$FFD0D4
Level_data_addr_RAM.SolidData1:	equ	$FFD0D8
Level_data_addr_RAM.SolidData2:	equ	$FFD0DC
Level_data_addr_RAM.ObjectsRAM:	equ	$FFD0E0
Level_data_addr_RAM.ObjectsData1:	equ	$FFD0E4
Level_data_addr_RAM.ObjectsData2:	equ	$FFD0E8
Level_data_addr_RAM.RingsRAM:	equ	$FFD0EC
Level_data_addr_RAM.RingsData1:	equ	$FFD0F0
Level_data_addr_RAM.RingsData2:	equ	$FFD0F4
Level_data_addr_RAM.PLC1:	equ	$FFD0F8
Level_data_addr_RAM.PLC2:	equ	$FFD0FC
Level_data_addr_RAM.PLCAnimals:	equ	$FFD100
Level_data_addr_RAM.xstart:	equ	$FFD104
Level_data_addr_RAM.xend:	equ	$FFD106
Level_data_addr_RAM.ystart:	equ	$FFD108
Level_data_addr_RAM.yend:	equ	$FFD10A
Level_data_addr_RAM.WaterHeight:	equ	$FFD10C
Level_data_addr_RAM.SPal:	equ	$FFD10E
Level_data_addr_RAM.KPal:	equ	$FFD10F
Level_data_addr_RAM.WaterSPal:	equ	$FFD110
Level_data_addr_RAM.WaterKPal:	equ	$FFD111
Level_data_addr_RAM.SonLoc:	equ	$FFD112
Level_data_addr_RAM.KnuxLoc:	equ	$FFD116
Level_data_addr_RAM.Debug:	equ	$FFD11A
KosPlus_decomp_queue_count:	equ	$FFD11E
KosPlus_decomp_stored_registers:	equ	$FFD120
KosPlus_decomp_stored_SR:	equ	$FFD138
KosPlus_decomp_bookmark:	equ	$FFD13A
KosPlus_decomp_queue:	equ	$FFD13E
KosPlus_modules_left:	equ	$FFD15E
KosPlus_last_module_size:	equ	$FFD160
KosPlus_module_queue:	equ	$FFD162
Target_water_palette_line_1:	equ	$FFD222
Target_water_palette_line_2:	equ	$FFD242
Target_water_palette_line_3:	equ	$FFD262
Target_water_palette_line_4:	equ	$FFD282
Water_palette_line_1:	equ	$FFD2A2
Water_palette_line_2:	equ	$FFD2C2
Water_palette_line_3:	equ	$FFD2E2
Water_palette_line_4:	equ	$FFD302
Normal_palette_line_1:	equ	$FFD322
Normal_palette_line_2:	equ	$FFD342
Normal_palette_line_3:	equ	$FFD362
Normal_palette_line_4:	equ	$FFD382
Target_palette_line_1:	equ	$FFD3A2
Target_palette_line_2:	equ	$FFD3C2
Target_palette_line_3:	equ	$FFD3E2
Target_palette_line_4:	equ	$FFD402
Oscillation_Control:	equ	$FFD422
Oscillating_Data:	equ	$FFD426
Anim_Counters:	equ	$FFD46E
AIZ_vine_angle:	equ	$FFD47E
Ending_player:	equ	$FFD480
Level_trigger_array:	equ	$FFD480
Spikes_frame_timer:	equ	$FFD490
Spikes_frame:	equ	$FFD491
Rings_frame_timer:	equ	$FFD492
Rings_frame:	equ	$FFD493
Ring_spill_anim_counter:	equ	$FFD494
Ring_spill_anim_frame:	equ	$FFD495
Ring_spill_anim_accum:	equ	$FFD496
Stack_contents:	equ	$FFD498
V_int_run_count:	equ	$FFD598
Current_zone:	equ	$FFD59C
Current_act:	equ	$FFD59D
Apparent_zone:	equ	$FFD59E
Apparent_act:	equ	$FFD59F
Player_mode:	equ	$FFD5A0
Player_option:	equ	$FFD5A2
Life_count:	equ	$FFD5A4
Current_special_stage:	equ	$FFD5A5
Continue_count:	equ	$FFD5A6
Chaos_emerald_count:	equ	$FFD5A8
Collected_emeralds_array:	equ	$FFD5AA
Special_bonus_entry_flag:	equ	$FFD5B2
Next_extra_life_score:	equ	$FFD5B4
Debug_saved_mappings:	equ	$FFD5B8
Debug_saved_priority:	equ	$FFD5BC
Debug_saved_art_tile:	equ	$FFD5BE
Last_star_post_hit:	equ	$FFD5C1
Current_music:	equ	$FFD5C2
Palette_fade_timer:	equ	$FFD5C4
Respawn_table_keep:	equ	$FFD5C7
Intro_flag:	equ	$FFD5C8
Music_disable_flag:	equ	$FFD5C9
Sound_disable_flag:	equ	$FFD5CA
Graphics_flags:	equ	$FFD5CB
Level_select_flag:	equ	$FFD5CC
Debug_mode_flag:	equ	$FFD5CD
SBZ2_player_roll:	equ	$FFD5CE
Japan_credits_flag:	equ	$FFD5CF
Debug_cheat_flag:	equ	$FFD5D0
Game_mode_last:	equ	$FFD5D1
Time_over_flag:	equ	$FFD5D2
Extra_life_flags:	equ	$FFD5D3
Update_HUD_life_count:	equ	$FFD5D4
Update_HUD_ring_count:	equ	$FFD5D5
Update_HUD_timer:	equ	$FFD5D6
Update_HUD_score:	equ	$FFD5D7
Ring_count:	equ	$FFD5D8
Timer:	equ	$FFD5DA
Timer_minute:	equ	$FFD5DB
Timer_second:	equ	$FFD5DC
Timer_frame:	equ	$FFD5DD
Score:	equ	$FFD5DE
HUD_RAM.xpos:	equ	$FFD5E2
HUD_RAM.ypos:	equ	$FFD5E4
HUD_RAM.status:	equ	$FFD5E6
GameOver_RAM.xpos:	equ	$FFD5E8
GameOver_RAM.ypos:	equ	$FFD5EA
GameOver_RAM.xpos2:	equ	$FFD5EC
GameOver_RAM.mappings:	equ	$FFD5EE
GameOver_RAM.timer:	equ	$FFD5F2
GameOver_RAM.status:	equ	$FFD5F4
GameOver_RAM.frame:	equ	$FFD5F5
DecimalScoreRAM:	equ	$FFD5F6
DecimalScoreRAM2:	equ	$FFD5FA
Saved_zone_and_act:	equ	$FFD5FE
Saved_apparent_zone_and_act:	equ	$FFD600
Saved_X_pos:	equ	$FFD602
Saved_Y_pos:	equ	$FFD604
Saved_ring_count:	equ	$FFD606
Saved_timer:	equ	$FFD608
Saved_art_tile:	equ	$FFD60C
Saved_solid_bits:	equ	$FFD60E
Saved_camera_X_pos:	equ	$FFD610
Saved_camera_Y_pos:	equ	$FFD612
Saved_mean_water_level:	equ	$FFD614
Saved_water_full_screen_flag:	equ	$FFD616
Saved_extra_life_flags:	equ	$FFD617
Saved_camera_max_Y_pos:	equ	$FFD618
Saved_dynamic_resize:	equ	$FFD61A
Saved_waterdynamic_resize:	equ	$FFD61E
Saved_status_secondary:	equ	$FFD622
Saved_last_star_post_hit:	equ	$FFD623
Saved2_zone_and_act:	equ	$FFD624
Saved2_apparent_zone_and_act:	equ	$FFD626
Saved2_X_pos:	equ	$FFD628
Saved2_Y_pos:	equ	$FFD62A
Saved2_ring_count:	equ	$FFD62C
Saved2_timer:	equ	$FFD62E
Saved2_art_tile:	equ	$FFD632
Saved2_solid_bits:	equ	$FFD634
Saved2_camera_X_pos:	equ	$FFD636
Saved2_camera_Y_pos:	equ	$FFD638
Saved2_mean_water_level:	equ	$FFD63A
Saved2_water_full_screen_flag:	equ	$FFD63C
Saved2_extra_life_flags:	equ	$FFD63D
Saved2_camera_max_Y_pos:	equ	$FFD63E
Saved2_dynamic_resize:	equ	$FFD640
Saved2_waterdynamic_resize:	equ	$FFD644
Saved2_status_secondary:	equ	$FFD648
Saved2_last_star_post_hit:	equ	$FFD649
Demo_start_button:	equ	$FFD64A
Demo_mode_flag:	equ	$FFD64B
Demo_data_addr:	equ	$FFD64C
Demo_hold_counter:	equ	$FFD650
Demo_hold_buttons:	equ	$FFD651
Demo_number:	equ	$FFD652
Next_demo_number:	equ	$FFD654
Demo_button_index:	equ	$FFD656
Demo_button_index_2P:	equ	$FFD658
Checksum_string:	equ	$FFD65A
V_int_jump:	equ	$FFD65E
V_int_addr:	equ	$FFD660
H_int_jump:	equ	$FFD664
H_int_addr:	equ	$FFD666
