; ===========================================================================
; Render objects data
; ===========================================================================

		include "Objects/Pylon/Load Pylon.asm"
		include "Objects/HUD/Load HUD.asm"
		include "Data/Screens/Special Stage/Load HUD.asm"
		include "Objects/Game Over/Load Game Over.asm"

; ===========================================================================
; Main objects data
; ===========================================================================

		include "Objects/Rings/Rings.asm"
		include "Objects/Path Swap/Path Swap.asm"
		include "Objects/Monitor/Monitor.asm"
		include "Objects/Hidden Monitor/Hidden Monitor.asm"
		include "Objects/Spring/Spring.asm"
		include "Objects/Spring/Spring(Retracting).asm"
		include "Objects/Spikes/Spikes.asm"
		include "Objects/Auto Spin/Auto Spin.asm"
		include "Objects/Invisible Blocks/Invisible Block(Solid).asm"
		include "Objects/Invisible Blocks/Invisible Block(Hurt).asm"
		include "Objects/Invisible Blocks/Invisible Block(Kill).asm"
		include "Objects/Title Card/Title Card.asm"
		include "Objects/Signpost/Signpost.asm"
		include "Objects/Results/Results.asm"
		include "Objects/Explosion/Boss Explosion.asm"
		include "Objects/Explosion/Explosion.asm"
		include "Objects/Bubbler/Bubbler.asm"
		include "Objects/Count Down/Count Down.asm"
		include "Objects/Wave Splash/Wave Splash.asm"
		include "Objects/Water Splash/Water Splash.asm"
		include "Objects/StarPost/StarPost.asm"
		include "Objects/Big Ring/Big Ring.asm"
		include "Objects/Button/Button.asm"
		include "Objects/Animals/Animals.asm"
		include "Objects/Egg Capsule/Egg Capsule.asm"
		include "Objects/Hidden Bonus/Hidden Bonus.asm"
		include "Objects/Still Sprites/Still Sprites.asm"
		include "Objects/Still Sprites/Still Sprites(Animated).asm"
		include "Objects/Foreground Plant/Foreground Plant.asm"
		include "Objects/Twisted Ramp/Twisted Ramp.asm"
		include "Objects/Updraft/Updraft.asm"
		include "Objects/Cork Floor/Cork Floor.asm"
		include "Objects/Sinking Mud/Sinking Mud.asm"
		include "Objects/Sprite Mask/Sprite Mask.asm"
		include "Objects/Start New Level/Start New Level.asm"
		include "Objects/Palette Script/Palette Script.asm"

; ===========================================================================
; Levels objects data
; ===========================================================================

		include "Objects/Crabmeat/Crabmeat.asm"
		include "Objects/Chopper/Chopper.asm"
		include "Objects/Buzz Bomber/Buzz Bomber.asm"
		include "Objects/Moto Bug/Moto Bug.asm"
		include "Objects/Newtron/Newtron.asm"
		include "Objects/Bridge/Bridge.asm"
		include "Objects/Collapsing Platform/Collapsing Platform.asm"
		include "Objects/Swinging Platform/Swinging Platform.asm"
		include "Objects/Breakable Wall/Breakable Wall.asm"
		include "Objects/Floating Platform/Floating Platform.asm"
		include "Objects/Purple Rock/Purple Rock.asm"
		include "Objects/Spike Pole/Spike Pole.asm"
		include "Objects/Edge Walls/Edge Walls.asm"
		include "Objects/Water Sound/Water Sound.asm"
		include "Objects/Basaran/Basaran.asm"
		include "Objects/Caterkiller/Caterkiller.asm"
		include "Objects/Yadrin/Yadrin.asm"
		include "Objects/Roller/Roller.asm"
		include "Objects/Splats/Splats.asm"
		include "Objects/Bumper/Bumper.asm"
		include "Objects/Large Grassy Platforms/Large Grassy Platforms.asm"
		include "Objects/Burning Grass/Burning Grass.asm"
		include "Objects/Lava Ball/Lava Ball.asm"
		include "Objects/Lava Wall/Lava Wall.asm"
		include "Objects/Moving Blocks/Moving Blocks.asm"
		include "Objects/Chained Stompers/Chained Stompers.asm"
		include "Objects/Chained Stompers/Sideways Stomper.asm"
		include "Objects/Glass Block/Glass Block.asm"
		include "Objects/Marble Brick/Marble Brick.asm"
		include "Objects/Smash Block/Smash Block.asm"
		include "Objects/Collapsing Floor/Collapsing Floor.asm"
		include "Objects/Lava Geyser/Lava Geyser.asm"
		include "Objects/Pushable Blocks/Pushable Blocks.asm"
		include "Objects/Floating Blocks and Doors/Floating Blocks and Doors.asm"
		include "Objects/Big Spiked Ball/Big Spiked Ball.asm"
		include "Objects/Spiked Ball and Chain/Spiked Ball and Chain(SYZ).asm"
		include "Objects/Spiked Ball and Chain/Spiked Ball and Chain(LZ).asm"
		include "Objects/Flapping Door/Flapping Door.asm"
		include "Objects/Pole that Breaks/Pole that Breaks.asm"
		include "Objects/Labyrinth Blocks/Labyrinth Blocks.asm"
		include "Objects/Labyrinth Waterfalls/Labyrinth Waterfalls.asm"
		include "Objects/Labyrinth Conveyor/Labyrinth Conveyor.asm"
		include "Objects/Stomper and Door/Stomper and Door.asm"
		include "Objects/Gargoyle/Gargoyle.asm"
		include "Objects/Harpoon/Harpoon.asm"
		include "Objects/Burrobot/Burrobot.asm"
		include "Objects/Jaws/Jaws.asm"
		include "Objects/Orbinaut/Orbinaut.asm"
		include "Objects/Staircase/Staircase.asm"
		include "Objects/Bomb/Bomb.asm"
		include "Objects/Fan/Fan.asm"
		include "Objects/Seesaw/Seesaw.asm"
		include "Objects/Circling Platform/Circling Platform.asm"
		include "Objects/Elevators/Elevators.asm"
		include "Objects/Ball Hog/Ball Hog.asm"
		include "Objects/Electrocuter/Electrocuter.asm"
		include "Objects/Flamethrower/Flamethrower.asm"
		include "Objects/Spinning Platforms/Spinning Platforms.asm"
		include "Objects/Saws and Pizza Cutters/Saws and Pizza Cutters.asm"
		include "Objects/Rotating Junction/Rotating Junction.asm"
		include "Objects/Running Disc/Running Disc.asm"
		include "Objects/Girder Block/Girder Block.asm"
		include "Objects/Conveyor Belt/Conveyor Belt.asm"
		include "Objects/Vanishing Platforms/Vanishing Platforms.asm"
		include "Objects/Small Door/Small Door.asm"
		include "Objects/Spin Platform Conveyor/Spin Platform Conveyor.asm"
		include "Objects/Teleporter/Teleporter.asm"

; ===========================================================================
; Bosses objects data
; ===========================================================================

		include "Objects/Robotnik/Robotnik.asm"
		include "Objects/Scrap Eggman/Scrap Eggman.asm"
		include "Objects/Bosses/GHZ3/Boss.asm"
		include "Objects/Bosses/MZ3/Boss.asm"
		include "Objects/Bosses/SYZ3/Boss.asm"
		include "Objects/Bosses/LZ3/Boss.asm"
		include "Objects/Bosses/SLZ3/Boss.asm"
		include "Objects/Bosses/FZ/Boss.asm"
